apiVersion: v1
kind: Service
metadata:
  name: node-api
  labels:
    app: node-api
spec:
  type: LoadBalancer
  selector:
    app: node-api
  ports:
    - protocol: TCP
      port: 80        # Public port exposed by ELB
      targetPort: 3000 # Port your Node.js app listens on inside the pod
